# 1 = enabled, 0 = disabled
SYSTEMIZE_DANGBEI=1
SYSTEMIZE_TV_SETTINGS=1
SYSTEMIZE_HOME_BRIDGE=1
PREFER_DANGBEI_HOME=1
DISABLE_FALLBACK_HOME=1
DISABLE_FACTORY_HOME=0
DISABLE_OTA=1
DISABLE_AD_COMPONENTS=1
APPLY_AD_SETTINGS=1
